version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - errorlint
    - gosec
    - gocritic
    - testifylint
    - nilerr
    - forcetypeassert
    - contextcheck
    - nosprintfhostport

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
