version: 2

project_name: k8s-mongo-labeler-sidecar

builds:
  - id: labeler-binary
    main: ./main.go
    no_unique_dist_dir: true
    binary: "k8s-mongo-labeler-sidecar-{{ .Os }}-{{ .Arch }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: labeler-archives
    ids:
      - labeler-binary
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  prerelease: auto
